import{a as b,S as w,i as m}from"./assets/vendor-06b1bbdf.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const u of r.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const S="43248873-3ce9b820c5f26b6ef0afaa018",L="https://pixabay.com/api/";async function p(e,s=1,o=15){const a={key:S,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:s,per_page:o};try{const r=(await b.get(L,{params:a})).data;if(r.hits.length===0)throw new Error("Sorry, there are no images matching your search query. Please try again!");return{images:r.hits,totalHits:r.totalHits}}catch{throw new Error("Network response was not ok")}}const d=document.querySelector(".gallery");function g(e){d.innerHTML="",e.forEach(o=>{const a=`
            <div class="gallery-item">
                <a href="${o.largeImageURL}">
                    <img src="${o.webformatURL}" alt="${o.tags}" />
                </a>
                <div class="image-info">
                    <p>Likes: ${o.likes}</p>
                    <p>Views: ${o.views}</p>
                    <p>Comments: ${o.comments}</p>
                    <p>Downloads: ${o.downloads}</p>
                </div>
            </div>
        `;d.insertAdjacentHTML("beforeend",a)}),new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const v=document.querySelector(".search-form"),h=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");v.addEventListener("submit",E);f.addEventListener("click",H);let n=1,y="";const i=15;async function E(e){e.preventDefault();const s=document.querySelector(".search-input"),o=s.value.trim();if(!o){c("Search query cannot be empty");return}h.style.display="block",d.innerHTML="",n=1,y=o;try{const{images:a,totalHits:t}=await p(y,n,i);I(a,t),l(!0)}catch(a){P(a),l(!1)}s.value=""}function c(e){m.error({title:"Error",message:e})}function q(e){m.success({title:"Success",message:e})}function I(e,s){h.style.display="none",g(e),q("Images loaded successfully"),n*i>=s&&(l(!1),c("We're sorry, but you've reached the end of search results."))}function P(e){h.style.display="none",c(e.message)}function l(e){e?f.style.display="block":f.style.display="none"}async function H(){n+=1;try{const{images:e,totalHits:s}=await p(y,n,i);M(e),n*i>=s&&(l(!1),c("We're sorry, but you've reached the end of search results."))}catch(e){c(e.message)}}function M(e){g(e),T()}function T(){const e=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
